package com.odos.odos_server_v2.domain.notification.entity.Enum;

public enum NotificationType {
  FRIEND_REQUEST,
  FRIEND_ACCEPT,
  FRIEND_DIARY_CREATED,
  MY_DIARY_COMMENTED,
  MY_COMMENT_REPLIED,
  DIARY_LIKE_MILESTONE,
  CHALLENGE_APPLIED,
  CHALLENGE_APPROVED,
  CHALLENGE_REJECTED,
  CHALLENGE_POKE,
  CHALLENGE_DIARY_REMINDER
}
