-- 친구 기능 테이블 생성
-- V13__add_friend_tables.sql

CREATE TABLE friend_request (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_member_id BIGINT NOT NULL,
    to_member_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_friend_request_from_to UNIQUE (from_member_id, to_member_id),
    CONSTRAINT fk_friend_request_from_member FOREIGN KEY (from_member_id) REFERENCES member (member_id) ON DELETE CASCADE,
    CONSTRAINT fk_friend_request_to_member FOREIGN KEY (to_member_id) REFERENCES member (member_id) ON DELETE CASCADE
);

CREATE TABLE friend (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    friend_member_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_friend_member_friend UNIQUE (member_id, friend_member_id),
    CONSTRAINT fk_friend_member FOREIGN KEY (member_id) REFERENCES member (member_id) ON DELETE CASCADE,
    CONSTRAINT fk_friend_friend_member FOREIGN KEY (friend_member_id) REFERENCES member (member_id) ON DELETE CASCADE
);

CREATE TABLE block_list (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    blocked_member_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_block_list_member_blocked UNIQUE (member_id, blocked_member_id),
    CONSTRAINT fk_block_list_member FOREIGN KEY (member_id) REFERENCES member (member_id) ON DELETE CASCADE,
    CONSTRAINT fk_block_list_blocked_member FOREIGN KEY (blocked_member_id) REFERENCES member (member_id) ON DELETE CASCADE
);
