CREATE TABLE comment_report (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  type varchar(20) DEFAULT NULL,
  content varchar(255) DEFAULT NULL,
  created_at timestamp(6) NOT NULL,
  member_id bigint NOT NULL,
  comment_id bigint NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT FK_comment_report_member FOREIGN KEY (member_id) REFERENCES member (member_id),
  CONSTRAINT FK_comment_report_comment FOREIGN KEY (comment_id) REFERENCES comment (id)
);

CREATE INDEX idx_comment_report_member ON comment_report (member_id);
CREATE INDEX idx_comment_report_comment ON comment_report (comment_id);
