CREATE TABLE notification_event (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamp(6) NOT NULL,
  actor_member_id BIGINT NULL,
  category VARCHAR(20) NOT NULL,
  type VARCHAR(40) NOT NULL,
  message TEXT NOT NULL,
  target_type VARCHAR(30) NOT NULL,
  target_id BIGINT NULL,
  grouped_count INT NULL,
  PRIMARY KEY (id),
  CONSTRAINT fk_notification_event_actor_member FOREIGN KEY (actor_member_id) REFERENCES member (member_id)
);

ALTER TABLE notification
  ADD COLUMN notification_event_id BIGINT NULL;

ALTER TABLE notification
  ADD CONSTRAINT fk_notification_event FOREIGN KEY (notification_event_id) REFERENCES notification_event (id);

INSERT INTO notification_event (created_at, actor_member_id, category, type, message, target_type, target_id, grouped_count)
SELECT created_at, actor_member_id, category, type, message, target_type, target_id, grouped_count
FROM notification;

UPDATE notification n
SET notification_event_id = e.id
FROM notification_event e
WHERE n.notification_event_id IS NULL
  AND n.created_at = e.created_at
  AND n.actor_member_id IS NOT DISTINCT FROM e.actor_member_id
  AND n.category = e.category
  AND n.type = e.type
  AND n.target_type = e.target_type
  AND n.target_id IS NOT DISTINCT FROM e.target_id;

CREATE INDEX idx_notification_event_created_at ON notification_event (created_at);
