-- PostgreSQL baseline schema for ODOS

DROP TABLE IF EXISTS challenge_goal CASCADE;
DROP TABLE IF EXISTS challenge_like CASCADE;
DROP TABLE IF EXISTS diary_goal CASCADE;
DROP TABLE IF EXISTS diary_image CASCADE;
DROP TABLE IF EXISTS diary_like CASCADE;
DROP TABLE IF EXISTS diary_report CASCADE;
DROP TABLE IF EXISTS interest CASCADE;
DROP TABLE IF EXISTS participant CASCADE;
DROP TABLE IF EXISTS diary CASCADE;
DROP TABLE IF EXISTS challenge CASCADE;
DROP TABLE IF EXISTS member CASCADE;

CREATE TABLE member (
  member_id bigint GENERATED BY DEFAULT AS IDENTITY,
  birth date DEFAULT NULL,
  email varchar(255) NOT NULL,
  gender varchar(255) DEFAULT NULL,
  is_public boolean DEFAULT NULL,
  job varchar(255) DEFAULT NULL,
  nickname varchar(255) DEFAULT NULL,
  nickname_last_modified_at timestamp DEFAULT NULL,
  profile_url varchar(255) DEFAULT NULL,
  refresh_token varchar(255) DEFAULT NULL,
  role varchar(255) DEFAULT NULL,
  signup_route varchar(255) DEFAULT NULL,
  social_id varchar(255) DEFAULT NULL,
  CONSTRAINT pk_member PRIMARY KEY (member_id),
  CONSTRAINT ukmbmcqelty0fbrvxp1q58dn57t UNIQUE (email)
);

CREATE TABLE challenge (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  category varchar(255) DEFAULT NULL,
  description varchar(255) DEFAULT NULL,
  end_date date DEFAULT NULL,
  max_participants_cnt bigint DEFAULT NULL,
  start_date date DEFAULT NULL,
  title varchar(255) DEFAULT NULL,
  type varchar(255) DEFAULT NULL,
  host_member_id bigint DEFAULT NULL,
  CONSTRAINT pk_challenge PRIMARY KEY (id)
);

CREATE TABLE participant (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  status varchar(255) DEFAULT NULL,
  challenge_id bigint DEFAULT NULL,
  member_id bigint DEFAULT NULL,
  CONSTRAINT pk_participant PRIMARY KEY (id)
);

CREATE TABLE challenge_goal (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  content varchar(255) DEFAULT NULL,
  participant_id bigint DEFAULT NULL,
  CONSTRAINT pk_challenge_goal PRIMARY KEY (id)
);

CREATE TABLE challenge_like (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  challenge_id bigint DEFAULT NULL,
  member_id bigint DEFAULT NULL,
  CONSTRAINT pk_challenge_like PRIMARY KEY (id)
);

CREATE TABLE diary (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  completed_date date DEFAULT NULL,
  content text,
  created_date timestamp DEFAULT NULL,
  feeling varchar(255) DEFAULT NULL,
  is_all_goals_completed boolean DEFAULT NULL,
  is_deleted boolean DEFAULT NULL,
  is_public boolean DEFAULT NULL,
  title varchar(255) DEFAULT NULL,
  challenge_id bigint DEFAULT NULL,
  member_id bigint DEFAULT NULL,
  CONSTRAINT pk_diary PRIMARY KEY (id)
);

CREATE TABLE diary_goal (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  is_completed boolean DEFAULT NULL,
  challenge_goal_id bigint DEFAULT NULL,
  diary_id bigint DEFAULT NULL,
  CONSTRAINT pk_diary_goal PRIMARY KEY (id)
);

CREATE TABLE diary_image (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  url varchar(255) DEFAULT NULL,
  diary_id bigint DEFAULT NULL,
  CONSTRAINT pk_diary_image PRIMARY KEY (id)
);

CREATE TABLE diary_like (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  diary_id bigint DEFAULT NULL,
  member_id bigint DEFAULT NULL,
  CONSTRAINT pk_diary_like PRIMARY KEY (id)
);

CREATE TABLE diary_report (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  content varchar(255) DEFAULT NULL,
  type varchar(255) DEFAULT NULL,
  diary_id bigint DEFAULT NULL,
  member_id bigint DEFAULT NULL,
  CONSTRAINT pk_diary_report PRIMARY KEY (id)
);

CREATE TABLE interest (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  category varchar(255) DEFAULT NULL,
  member_id bigint DEFAULT NULL,
  CONSTRAINT pk_interest PRIMARY KEY (id)
);
