-- 일지 시청 기록 테이블 생성
-- V14__add_diary_view_log.sql

CREATE TABLE diary_view_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    member_id BIGINT NOT NULL,
    diary_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uk_diary_view_log_member_diary UNIQUE (member_id, diary_id),
    CONSTRAINT fk_diary_view_log_member FOREIGN KEY (member_id) REFERENCES member (member_id) ON DELETE CASCADE,
    CONSTRAINT fk_diary_view_log_diary FOREIGN KEY (diary_id) REFERENCES diary (id) ON DELETE CASCADE
);
