CREATE TABLE refresh_token (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    member_id BIGINT NOT NULL,
    refresh_token VARCHAR(512) NOT NULL,
    revoked BOOLEAN NOT NULL DEFAULT FALSE,
    revoked_at TIMESTAMP(6) DEFAULT NULL,
    expires_at TIMESTAMP(6) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    CONSTRAINT uk_refresh_token_token UNIQUE (refresh_token),
    CONSTRAINT fk_refresh_token_member FOREIGN KEY (member_id) REFERENCES member (member_id) ON DELETE CASCADE
);

CREATE INDEX idx_refresh_token_member_id ON refresh_token (member_id);
