CREATE TABLE challenge_poke (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    challenge_id BIGINT NOT NULL,
    actor_member_id BIGINT NOT NULL,
    receiver_member_id BIGINT NOT NULL,
    poked_date DATE NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    CONSTRAINT uk_challenge_poke_daily UNIQUE (challenge_id, actor_member_id, receiver_member_id, poked_date),
    CONSTRAINT fk_challenge_poke_challenge FOREIGN KEY (challenge_id) REFERENCES challenge (id),
    CONSTRAINT fk_challenge_poke_actor FOREIGN KEY (actor_member_id) REFERENCES member (member_id),
    CONSTRAINT fk_challenge_poke_receiver FOREIGN KEY (receiver_member_id) REFERENCES member (member_id)
);

CREATE INDEX idx_challenge_poke_receiver_date ON challenge_poke (receiver_member_id, poked_date);
