-- 고정목표(FIXED) 챌린지의 "챌린지에 매달린 목표"를 챌린지 단위로 보관하는 테이블.
-- challenge_goal 은 참여자별 목표 + 일지 연결 역할 그대로 유지하고,
-- fixed_challenge_goal 은 참여자가 들어올 때 challenge_goal 로 복제되는 원본 목표를 담는다.
CREATE TABLE fixed_challenge_goal (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  content varchar(255) DEFAULT NULL,
  challenge_id bigint DEFAULT NULL,
  CONSTRAINT pk_fixed_challenge_goal PRIMARY KEY (id)
);

-- 기존 고정목표 챌린지 백필:
-- 각 FIXED 챌린지의 호스트 participant 가 가진 challenge_goal 을 fixed_challenge_goal 로 복사한다.
-- challenge_goal(참여자 목표 + 일지 연결)은 그대로 유지한다.
INSERT INTO fixed_challenge_goal (content, challenge_id)
SELECT cg.content, c.id
FROM challenge c
JOIN participant p
  ON p.challenge_id = c.id
  AND p.member_id = c.host_member_id
  AND p.status = 'HOST'
JOIN challenge_goal cg
  ON cg.participant_id = p.id
WHERE c.goal_type = 'FIXED';
