-- 홈 팝업(어드민 설정). 게시 기간(start_date~end_date) + is_active 로 노출 판정.
CREATE TABLE popup (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  popup_key varchar(36) NOT NULL,
  image_url varchar(512) NOT NULL,
  cta_text varchar(255) NOT NULL,
  link_url varchar(512) NOT NULL,
  title varchar(255) DEFAULT NULL,
  start_date date NOT NULL,
  end_date date NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  CONSTRAINT pk_popup PRIMARY KEY (id),
  CONSTRAINT uk_popup_key UNIQUE (popup_key)
);

-- 오늘 게시 중 조회(is_active + start_date <= today <= end_date)용 인덱스.
CREATE INDEX idx_popup_active_dates ON popup (is_active, start_date, end_date);
