CREATE TABLE native_session_code (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    member_id BIGINT NOT NULL,
    code_hash VARCHAR(64) NOT NULL,
    expires_at TIMESTAMP(6) NOT NULL,
    used_at TIMESTAMP(6) DEFAULT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    CONSTRAINT uk_native_session_code_hash UNIQUE (code_hash),
    CONSTRAINT fk_native_session_code_member
        FOREIGN KEY (member_id) REFERENCES member (member_id) ON DELETE CASCADE
);

CREATE INDEX idx_native_session_code_member_id ON native_session_code (member_id);
CREATE INDEX idx_native_session_code_expires_at ON native_session_code (expires_at);
