-- 관리자 공지. is_pinned(고정) 공지를 목록 최상단에 노출한다.
-- 정렬: 고정 먼저(고정끼리는 등록순=오래된 게 위) → 비고정은 최신순.
-- author_member_id 는 작성 관리자 감사용(응답에는 노출하지 않음).
CREATE TABLE notice (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  title varchar(255) NOT NULL,
  content text NOT NULL,
  is_pinned boolean NOT NULL DEFAULT false,
  author_member_id bigint,
  created_at timestamp(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  updated_at timestamp(6),
  CONSTRAINT pk_notice PRIMARY KEY (id),
  CONSTRAINT fk_notice_author FOREIGN KEY (author_member_id) REFERENCES member (member_id) ON DELETE SET NULL
);

-- 목록 정렬(고정 우선) 조회용 인덱스.
CREATE INDEX idx_notice_pinned_created ON notice (is_pinned, created_at);
