CREATE TABLE banner (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  title varchar(255) NOT NULL,
  subtitle varchar(255) NOT NULL,
  image_url varchar(512) NOT NULL,
  link_url varchar(512) NOT NULL,
  start_date date NOT NULL,
  end_date date NOT NULL,
  created_at timestamp(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  CONSTRAINT pk_banner PRIMARY KEY (id)
);

CREATE INDEX idx_banner_dates ON banner (start_date, end_date);
