CREATE TABLE vote (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title varchar(255) NOT NULL,
  selection_type varchar(20) NOT NULL,
  vote_type varchar(20) NOT NULL,
  start_date date NOT NULL,
  end_date date NOT NULL,
  created_at timestamp(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  CONSTRAINT ck_vote_period CHECK (start_date <= end_date),
  CONSTRAINT ck_vote_selection_type CHECK (selection_type IN ('SINGLE', 'MULTIPLE')),
  CONSTRAINT ck_vote_type CHECK (vote_type IN ('PUBLIC', 'ADMIN_SURVEY'))
);

CREATE TABLE vote_option (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vote_id bigint NOT NULL REFERENCES vote(id) ON DELETE CASCADE,
  option_text varchar(255) NOT NULL,
  display_order integer NOT NULL,
  CONSTRAINT uk_vote_option_order UNIQUE (vote_id, display_order)
);

CREATE TABLE vote_response (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vote_id bigint NOT NULL REFERENCES vote(id) ON DELETE CASCADE,
  member_id bigint NOT NULL REFERENCES member(member_id),
  created_at timestamp(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  CONSTRAINT uk_vote_response_member UNIQUE (vote_id, member_id)
);

CREATE TABLE vote_response_selection (
  response_id bigint NOT NULL REFERENCES vote_response(id) ON DELETE CASCADE,
  option_id bigint NOT NULL REFERENCES vote_option(id) ON DELETE CASCADE,
  PRIMARY KEY (response_id, option_id)
);

CREATE INDEX idx_vote_type_dates ON vote (vote_type, start_date, end_date);
CREATE INDEX idx_vote_response_vote ON vote_response (vote_id);
CREATE INDEX idx_vote_selection_option ON vote_response_selection (option_id);
