CREATE TABLE device_token (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  member_id bigint NOT NULL,
  device_id varchar(255) NOT NULL,
  token varchar(512) NOT NULL,
  platform varchar(16) NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  updated_at timestamp(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  CONSTRAINT pk_device_token PRIMARY KEY (id),
  CONSTRAINT fk_device_token_member FOREIGN KEY (member_id) REFERENCES member (member_id),
  CONSTRAINT uq_device_token_device_id UNIQUE (device_id)
);

CREATE INDEX idx_device_token_member_active ON device_token (member_id, is_active);
