CREATE TABLE comment (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  content text NOT NULL,
  is_deleted boolean NOT NULL DEFAULT FALSE,
  created_at timestamp(6) NOT NULL,
  member_id bigint NOT NULL,
  diary_id bigint NOT NULL,
  parent_id bigint DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT FK_comment_member FOREIGN KEY (member_id) REFERENCES member (member_id),
  CONSTRAINT FK_comment_diary FOREIGN KEY (diary_id) REFERENCES diary (id),
  CONSTRAINT FK_comment_parent FOREIGN KEY (parent_id) REFERENCES comment (id)
);

CREATE INDEX idx_comment_member ON comment (member_id);
CREATE INDEX idx_comment_diary ON comment (diary_id);
CREATE INDEX idx_comment_parent ON comment (parent_id);
